<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Receipt</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; font-size: 14px; }
        .wrap { border: 1px solid #d1d5db; padding: 24px; }
        .center { text-align: center; }
        .title { font-size: 24px; font-weight: bold; margin-bottom: 6px; }
        .sub { font-size: 13px; color: #4b5563; margin-bottom: 20px; }
        .section { margin-top: 18px; }
        .row { margin-bottom: 10px; }
        .label { font-size: 12px; color: #6b7280; }
        .value { font-size: 14px; font-weight: bold; }
        .amount { font-size: 20px; font-weight: bold; }
        .status { color: #15803d; font-weight: bold; text-transform: uppercase; }
        .footer { margin-top: 28px; font-size: 12px; color: #6b7280; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        td { width: 50%; vertical-align: top; padding: 8px 0; }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="center">
            <div class="title">Mustey Digital Academy</div>
            <div class="sub">Payment Receipt</div>
        </div>

        <table>
            <tr>
                <td>
                    <div class="label">Student</div>
                    <div class="value">{{ $payment->user->name ?? '—' }}</div>
                    <div>{{ $payment->user->email ?? '—' }}</div>
                </td>
                <td>
                    <div class="label">Course</div>
                    <div class="value">{{ $payment->course->title ?? '—' }}</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="label">Reference</div>
                    <div class="value">{{ $payment->reference }}</div>
                </td>
                <td>
                    <div class="label">Gateway</div>
                    <div class="value">{{ strtoupper($payment->gateway) }}</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="label">Amount</div>
                    <div class="amount">₦{{ number_format($payment->amount) }}</div>
                </td>
                <td>
                    <div class="label">Status</div>
                    <div class="status">{{ $payment->status }}</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="label">Paid At</div>
                    <div class="value">
                        {{ $payment->paid_at ? $payment->paid_at->format('M j, Y g:i A') : ($payment->created_at?->format('M j, Y g:i A') ?? '—') }}
                    </div>
                </td>
                <td>
                    <div class="label">Currency</div>
                    <div class="value">{{ strtoupper($payment->currency) }}</div>
                </td>
            </tr>
        </table>

        <div class="footer">
            Generated by Mustey Digital Academy
        </div>
    </div>
</body>
</html>
