<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between flex-wrap gap-2">
            <h2 class="font-semibold text-xl text-slate-800 leading-tight">
                Certificate Verification
            </h2>

            <a href="{{ route('courses.index') }}"
               class="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 transition">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
                </svg>
                Back to Courses
            </a>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">

            <div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                <div class="p-6 sm:p-8 border-b border-slate-200 bg-slate-50">
                    <div class="flex items-center justify-center gap-2">
                        <span class="inline-flex items-center rounded-full bg-green-50 text-green-700 px-4 py-2 text-sm font-semibold">
                            Verified Certificate
                        </span>
                    </div>

                    <p class="text-center text-slate-600 mt-3">
                        This certificate is valid and was generated by
                        <span class="font-semibold">Mustey Digital Academy</span>.
                    </p>
                </div>

                <div class="p-6 sm:p-8 space-y-6">

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <div class="rounded-xl border border-slate-200 p-5">
                            <p class="text-xs uppercase tracking-widest text-slate-500">Student</p>
                            <p class="text-lg font-semibold text-slate-900 mt-1">
                                {{ $certificate->user->name ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-slate-500 mt-4">Course</p>
                            <p class="text-slate-900 mt-1 font-semibold">
                                {{ $certificate->course->title ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-slate-500 mt-4">Instructor</p>
                            <p class="text-slate-800 mt-1">
                                {{ optional(optional($certificate->course)->instructor)->name ?? '—' }}
                            </p>
                        </div>

                        <div class="rounded-xl border border-slate-200 p-5">
                            <p class="text-xs uppercase tracking-widest text-slate-500">Serial Code</p>
                            <p class="text-lg font-semibold text-slate-900 mt-1">
                                {{ $certificate->serial }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-slate-500 mt-4">Issued On</p>
                            <p class="text-slate-800 mt-1">
                                {{ optional($certificate->issued_at)->format('F j, Y') ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-slate-500 mt-4">Status</p>
                            <span class="inline-flex items-center rounded-full bg-green-50 text-green-700 px-3 py-1 text-xs font-semibold mt-2">
                                VALID
                            </span>
                        </div>
                    </div>

                    <div class="rounded-xl border border-dashed border-slate-200 p-5 bg-slate-50">
                        <p class="font-semibold text-slate-800">Verification Details</p>
                        <p class="text-sm text-slate-600 mt-1">
                            Certificate records are stored in the system database and can be verified anytime using the serial code.
                        </p>

                        <div class="mt-4 flex flex-wrap gap-2">
                            <span class="inline-flex items-center rounded-xl bg-white border border-slate-200 px-3 py-2 text-sm text-slate-700">
                                Serial: <span class="font-semibold ml-1">{{ $certificate->serial }}</span>
                            </span>

                            @if($certificate->course)
                                <a class="inline-flex items-center rounded-xl border border-slate-200 px-4 py-2 text-sm hover:bg-white transition"
                                   href="{{ route('courses.show', $certificate->course->id) }}">
                                    View Course
                                </a>
                            @endif
                        </div>
                    </div>

                </div>

                <div class="p-6 sm:p-8 bg-slate-50 border-t border-slate-200">
                    <p class="text-xs text-slate-500 text-center">
                        Powered by Mustey Digital Academy
                    </p>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>