<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between flex-wrap gap-2">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Certificate Verification
            </h2>

            <a href="{{ route('courses.index') }}" class="underline text-gray-600">
                ← Back to Courses
            </a>
        </div>
    </x-slot>

    <div class="py-10">
        <div class="max-w-4xl mx-auto sm:px-6 lg:px-8">

            <div class="bg-white shadow-sm sm:rounded-lg overflow-hidden">
                <div class="p-6 sm:p-8 border-b bg-gray-50">
                    <div class="flex items-center justify-center gap-2">
                        <span class="inline-flex items-center rounded-full bg-green-100 text-green-800 px-4 py-2 text-sm font-semibold">
                            ✅ Verified Certificate
                        </span>
                    </div>

                    <p class="text-center text-gray-600 mt-3">
                        This certificate is valid and was generated by
                        <span class="font-semibold">Nexdus Academy × Mustey Digital Academy</span>.
                    </p>
                </div>

                <div class="p-6 sm:p-8 space-y-6">

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <div class="rounded-lg border p-5">
                            <p class="text-xs uppercase tracking-widest text-gray-500">Student</p>
                            <p class="text-lg font-semibold text-gray-900 mt-1">
                                {{ $certificate->user->name ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-gray-500 mt-4">Course</p>
                            <p class="text-gray-900 mt-1 font-semibold">
                                {{ $certificate->course->title ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-gray-500 mt-4">Instructor</p>
                            <p class="text-gray-800 mt-1">
                                {{ optional(optional($certificate->course)->instructor)->name ?? '—' }}
                            </p>
                        </div>

                        <div class="rounded-lg border p-5">
                            <p class="text-xs uppercase tracking-widest text-gray-500">Serial Code</p>
                            <p class="text-lg font-semibold text-gray-900 mt-1">
                                {{ $certificate->serial }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-gray-500 mt-4">Issued On</p>
                            <p class="text-gray-800 mt-1">
                                {{ optional($certificate->issued_at)->format('F j, Y') ?? '—' }}
                            </p>

                            <p class="text-xs uppercase tracking-widest text-gray-500 mt-4">Status</p>
                            <span class="inline-flex items-center rounded-full bg-green-100 text-green-800 px-3 py-1 text-xs font-semibold mt-2">
                                ✅ VALID
                            </span>
                        </div>
                    </div>

                    <div class="rounded-lg border border-dashed p-5 bg-gray-50">
                        <p class="font-semibold text-gray-800">Verification Details</p>
                        <p class="text-sm text-gray-600 mt-1">
                            Certificate records are stored in the system database and can be verified anytime using the serial code.
                        </p>

                        <div class="mt-4 flex flex-wrap gap-2">
                            <span class="inline-flex items-center rounded-md bg-white border px-3 py-2 text-sm text-gray-700">
                                Serial: <span class="font-semibold ml-1">{{ $certificate->serial }}</span>
                            </span>

                            @if($certificate->course)
                                <a class="inline-flex items-center rounded-md border px-4 py-2 text-sm hover:bg-white"
                                   href="{{ route('courses.show', $certificate->course->id) }}">
                                    View Course
                                </a>
                            @endif
                        </div>
                    </div>

                </div>

                <div class="p-6 sm:p-8 bg-gray-50 border-t">
                    <p class="text-xs text-gray-500 text-center">
                        Powered by Nexdus Academy × Mustey Digital Academy
                    </p>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>
